<?php
// admin/report.php
session_start();
require_once __DIR__ . '/../config/db.php';
require_once __DIR__ . '/../vendor/fpdf/fpdf.php';

// ===== CEK LOGIN & ROLE ADMIN =====
if (!isset($_SESSION['user_id'])) {
    header('Location: /TUBES_2_Toko/auth/login.php');
    exit;
}

$user_id = (int)$_SESSION['user_id'];
$stmt = $mysqli->prepare("SELECT username, role FROM user WHERE id = ? LIMIT 1");
$stmt->bind_param('i', $user_id);
$stmt->execute();
$resUser = $stmt->get_result()->fetch_assoc();
$stmt->close();

if (!$resUser || $resUser['role'] !== 'admin') {
    header('Location: /TUBES_2_Toko/index.php');
    exit;
}

// ===== AMBIL DATA TRANSAKSI + DETAIL =====
// Ambil hanya transaksi yang sudah dibayar / selesai
$sql = "
    SELECT 
        t.id              AS transaction_id,
        t.total_price     AS transaction_total,
        t.status          AS transaction_status,
        t.date_created    AS transaction_date,
        u.username        AS username,
        
        dt.product_id,
        dt.quantity,
        dt.price          AS line_price,
        p.name            AS product_name
    FROM transactions t
    JOIN user u              ON t.user_id = u.id
    JOIN detail_transaction dt ON dt.transaction_id = t.id
    JOIN products p          ON p.id = dt.product_id
    WHERE t.status <> 'Belum Dibayar'
    ORDER BY t.id ASC, dt.id ASC
";

$result = $mysqli->query($sql);

// Kelompokkan per transaksi
$transactions = [];
$totalRevenue = 0;
$statusCount  = [];

if ($result) {
    while ($row = $result->fetch_assoc()) {
        $tid = $row['transaction_id'];

        if (!isset($transactions[$tid])) {
            $transactions[$tid] = [
                'id'        => $tid,
                'username'  => $row['username'],
                'total'     => (int)$row['transaction_total'],
                'status'    => $row['transaction_status'],
                'date'      => $row['transaction_date'],
                'items'     => []
            ];

            // summary
            $totalRevenue += (int)$row['transaction_total'];
            $statusKey = $row['transaction_status'];
            if (!isset($statusCount[$statusKey])) {
                $statusCount[$statusKey] = 0;
            }
            $statusCount[$statusKey]++;
        }

        $transactions[$tid]['items'][] = [
            'product_name' => $row['product_name'],
            'quantity'     => (int)$row['quantity'],
            'line_total'   => (int)$row['line_price'] * (int)$row['quantity'],
        ];
    }
    $result->free();
}

$totalOrders = count($transactions);

// ===== KONFIG FPDF =====
class PDF extends FPDF {}

$pdf = new PDF('L', 'mm', 'A4'); // Landscape
$pdf->SetTitle('Feyora_Sales_Report');
$pdf->AddPage();

// ===== LOGO & HEADER ATAS =====
$logoPath = __DIR__ . '/../assets/Logo Feyora.png'; // sesuaikan path logo

if (file_exists($logoPath)) {
    // letakkan logo di tengah
    $pdf->Image($logoPath, 120, 8, 50); // (x, y, width)
    $pdf->Ln(30);
} else {
    $pdf->Ln(10);
}

// Judul
$pdf->SetFont('Arial', 'B', 24);
$pdf->Cell(0, 12, 'Sales Report', 0, 1, 'L');
$pdf->Ln(2);

// Info kecil: tanggal & admin
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(0, 5, 'Generated at: ' . date('d M Y H:i'), 0, 1, 'L');
$pdf->Cell(0, 5, 'Generated by: ' . $resUser['username'], 0, 1, 'L');
$pdf->Ln(4);

// ===== HEADER TABEL =====
// Warna header (pink lembut)
// Lebar kolom (total +- 275)
$wId       = 15;
$wUser     = 35;
$wProduct  = 90;
$wQty      = 20;
$wTotal    = 35;
$wStatus   = 35;
$wDate     = 45;

// ===== ISI TABEL =====
// ===== ISI TABEL (MERGE VERTIKAL PER TRANSAKSI) =====
$rowH        = 8;          // tinggi 1 baris
$maxTableY   = 185;        // batas sebelum page break

// fungsi kecil untuk gambar header tabel (dipakai ulang setelah AddPage)
$printHeader = function() use ($pdf, $wId, $wUser, $wProduct, $wQty, $wTotal, $wStatus, $wDate) {
    $pdf->SetFillColor(255, 220, 220);
    $pdf->SetDrawColor(220, 150, 150);
    $pdf->SetLineWidth(0.3);
    $pdf->SetFont('Arial', 'B', 11);

    $pdf->Cell($wId,      10, 'ID',        1, 0, 'C', true);
    $pdf->Cell($wUser,    10, 'Username',  1, 0, 'C', true);
    $pdf->Cell($wProduct, 10, 'Products',  1, 0, 'C', true);
    $pdf->Cell($wQty,     10, 'Quantity',  1, 0, 'C', true);
    $pdf->Cell($wTotal,   10, 'Total',     1, 0, 'C', true);
    $pdf->Cell($wStatus,  10, 'Status',    1, 0, 'C', true);
    $pdf->Cell($wDate,    10, 'Date',      1, 1, 'C', true);

    $pdf->SetFont('Arial', '', 10);
};

$printHeader();

if (empty($transactions)) {
    $pdf->Cell(0, 10, 'No paid orders found.', 1, 1, 'C');
} else {
    foreach ($transactions as $t) {
        $items     = $t['items'];
        $rowCount  = max(1, count($items));
        $blockH    = $rowH * $rowCount; // tinggi blok transaksi

        // cek apakah muat di halaman, kalau tidak -> page baru + header
        if ($pdf->GetY() + $blockH > $maxTableY) {
            $pdf->AddPage();
            $printHeader();
        }

        // koordinat awal blok
        $xStart = $pdf->GetX();
        $yStart = $pdf->GetY();

        // ===== kolom ID & Username (merged) =====
        $pdf->Cell($wId,   $blockH, $t['id'],       1, 0, 'C');
        $pdf->Cell($wUser, $blockH, $t['username'], 1, 0, 'L');

        // posisi mulai kolom Products
        $xAfterUser = $pdf->GetX();

        // ===== kolom Products + Quantity (per item baris) =====
        $pdf->SetXY($xAfterUser, $yStart);

        if (!empty($items)) {
            $i = 0;
            foreach ($items as $item) {
                $pdf->Cell($wProduct, $rowH, $item['product_name'], 1, 0, 'L');
                $pdf->Cell($wQty,     $rowH, $item['quantity'],     1, 0, 'C');

                $i++;
                if ($i < $rowCount) {
                    // pindah ke baris berikutnya, tetap mulai di kolom Products
                    $pdf->Ln($rowH);
                    $pdf->SetX($xAfterUser);
                }
            }
        } else {
            // kalau tidak ada item (harusnya jarang terjadi)
            $pdf->Cell($wProduct, $blockH, '-', 1, 0, 'L');
            $pdf->Cell($wQty,     $blockH, '-', 1, 0, 'C');
        }

        // ===== kolom Total, Status, Date (merged) =====
        $xAfterQty = $xAfterUser + $wProduct + $wQty;
        $pdf->SetXY($xAfterQty, $yStart);

        $totalFmt = 'Rp ' . number_format($t['total'], 0, ',', '.');
        $dateFmt  = date('d M Y H:i', strtotime($t['date']));

        $pdf->Cell($wTotal,  $blockH, $totalFmt, 1, 0, 'R');
        $pdf->Cell($wStatus, $blockH, $t['status'], 1, 0, 'C');
        $pdf->Cell($wDate,   $blockH, $dateFmt, 1, 0, 'C');

        // pindahkan pointer ke bawah blok transaksi
        $pdf->SetXY($xStart, $yStart + $blockH);
    }
}

// ===== SUMMARY DI BAGIAN BAWAH =====
$pdf->Ln(8);
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(0, 7, 'Summary', 0, 1, 'L');

$pdf->SetFont('Arial', '', 10);

$pdf->Cell(60, 6, 'Total Orders:', 0, 0, 'L');
$pdf->Cell(40, 6, $totalOrders, 0, 1, 'L');

$pdf->Cell(60, 6, 'Total Revenue:', 0, 0, 'L');
$pdf->Cell(40, 6, 'Rp ' . number_format($totalRevenue, 0, ',', '.'), 0, 1, 'L');

$pdf->Ln(3);
$pdf->Cell(60, 6, 'Orders by Status:', 0, 1, 'L');

if (!empty($statusCount)) {
    foreach ($statusCount as $st => $cnt) {
        $pdf->Cell(60, 5, '- ' . $st, 0, 0, 'L');
        $pdf->Cell(40, 5, $cnt, 0, 1, 'L');
    }
} else {
    $pdf->Cell(60, 5, '- (none)', 0, 1, 'L');
}

// ===== OUTPUT PDF (AUTO DOWNLOAD) =====
$filename = 'Feyora_SalesReport_' . date('Ymd-His') . '.pdf';

header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Cache-Control: private, max-age=0, must-revalidate');
header('Pragma: public');

$pdf->Output('D', $filename);
exit;
